//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Purchase.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplyDtl_SettlementDtl
    {
        public int ApplyId { get; set; }
        public string ApplyTypeId { get; set; }
        public int ApplyContentId { get; set; }
        public int SettlementSeqNO { get; set; }
        public Nullable<int> QuotationId { get; set; }
        public Nullable<int> QuotationSeqNO { get; set; }
        public Nullable<decimal> SettleUnitPrice { get; set; }
        public Nullable<decimal> SettleCount { get; set; }
        public Nullable<decimal> SettleAmt { get; set; }
        public string Remark { get; set; }
        public string SettlementType { get; set; }
        public string InUserId { get; set; }
        public Nullable<System.DateTime> InDateTime { get; set; }
    }
}
