//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Purchase.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Constract
    {
        public int Id { get; set; }
        public string ConstractCode { get; set; }
        public string ConstractName { get; set; }
        public string PartAName { get; set; }
        public string PartAAddress { get; set; }
        public string PartAContacts { get; set; }
        public string PartATel { get; set; }
        public string PartAEmail { get; set; }
        public string PartAPostCode { get; set; }
        public string PartBName { get; set; }
        public string PartBAddress { get; set; }
        public string PartBContacts { get; set; }
        public string PartBTel { get; set; }
        public string PartBEmail { get; set; }
        public string PartBPostCode { get; set; }
        public string ExecuteRegion { get; set; }
        public string RecheckRate { get; set; }
        public string SampleCountAndQuota { get; set; }
        public string ProjectShortName_Fix { get; set; }
        public string CostDesc { get; set; }
        public string PlatformName { get; set; }
        public Nullable<System.DateTime> LastFinishDate { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public string buzhanshijian { get; set; }
        public string chezhanshijian { get; set; }
        public string yunshuluxian { get; set; }
        public string fuwuneirong { get; set; }
        public string xieyiyouxiaoshijian { get; set; }
        public string zhanshizhanlanweituoneirong { get; set; }
        public string yunshucheliangxinxi { get; set; }
        public string QuotationIdList { get; set; }
        public string QuotationRemark { get; set; }
        public int ProjectId { get; set; }
        public int SupplierId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string EmailSendUser { get; set; }
        public Nullable<System.DateTime> EmailSendDateTime { get; set; }
        public Nullable<int> TemplateId { get; set; }
        public string InUserId { get; set; }
        public Nullable<System.DateTime> InDateTime { get; set; }
        public string QuotationId2List { get; set; }
        public string Quotation2Remark { get; set; }
    }
}
