//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Purchase.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectCity
    {
        public int ProjectId { get; set; }
        public int SeqNO { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public string Responsibilites { get; set; }
        public string ProjectType { get; set; }
        public string ExcuteMode { get; set; }
        public string PurchaseType { get; set; }
        public string PurchaseMode { get; set; }
        public string SupplyService { get; set; }
        public string ItemName { get; set; }
        public Nullable<decimal> Count { get; set; }
        public string Remark { get; set; }
        public string DemandBookStatus { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CancelDateTime { get; set; }
        public Nullable<bool> EmailSendChk { get; set; }
        public string InUserId { get; set; }
        public Nullable<System.DateTime> InDateTime { get; set; }
    
        public virtual Projects Projects { get; set; }
    }
}
