//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Purchase.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projects
    {
        public Projects()
        {
            this.ProjectPerson = new HashSet<ProjectPerson>();
            this.ProjectCity = new HashSet<ProjectCity>();
        }
    
        public int Id { get; set; }
        public string ServiceTrade { get; set; }
        public string ProjectCode { get; set; }
        public string ProjectName { get; set; }
        public string ProjectShortName { get; set; }
        public string ModelType { get; set; }
        public string Step { get; set; }
        public string DepartmentCode { get; set; }
        public string Year { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string ExcuteType { get; set; }
        public string ServiceRegion { get; set; }
        public string CostDepartment { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> StatusDate { get; set; }
        public string Remark { get; set; }
        public string InUserId { get; set; }
        public Nullable<System.DateTime> InDateTime { get; set; }
    
        public virtual ICollection<ProjectPerson> ProjectPerson { get; set; }
        public virtual ICollection<ProjectCity> ProjectCity { get; set; }
    }
}
