//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Purchase.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PurchaseEntities : DbContext
    {
        public PurchaseEntities()
            : base("name=PurchaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccruedCharges> AccruedCharges { get; set; }
        public virtual DbSet<Apply> Apply { get; set; }
        public virtual DbSet<ApplyDtl> ApplyDtl { get; set; }
        public virtual DbSet<ApplyRecheckStatus> ApplyRecheckStatus { get; set; }
        public virtual DbSet<CapitalRequirement> CapitalRequirement { get; set; }
        public virtual DbSet<ConstractAttachment> ConstractAttachment { get; set; }
        public virtual DbSet<ConstractDtl> ConstractDtl { get; set; }
        public virtual DbSet<ConstractDtlCommonText> ConstractDtlCommonText { get; set; }
        public virtual DbSet<ConstractTemplate> ConstractTemplate { get; set; }
        public virtual DbSet<ConstractTemplateDtl> ConstractTemplateDtl { get; set; }
        public virtual DbSet<Contingency> Contingency { get; set; }
        public virtual DbSet<HiddenCode> HiddenCode { get; set; }
        public virtual DbSet<HiddenCodeType> HiddenCodeType { get; set; }
        public virtual DbSet<Mst_Department> Mst_Department { get; set; }
        public virtual DbSet<Mst_Position> Mst_Position { get; set; }
        public virtual DbSet<Quotation_QuotationMst> Quotation_QuotationMst { get; set; }
        public virtual DbSet<RecheckProcess> RecheckProcess { get; set; }
        public virtual DbSet<RecheckProcessExcept> RecheckProcessExcept { get; set; }
        public virtual DbSet<Requirement_Anfang_RequirementDtl0> Requirement_Anfang_RequirementDtl0 { get; set; }
        public virtual DbSet<Requirement_Anfang_RequirementDtl1> Requirement_Anfang_RequirementDtl1 { get; set; }
        public virtual DbSet<Requirement_Anfang_RequirementDtl2> Requirement_Anfang_RequirementDtl2 { get; set; }
        public virtual DbSet<Requirement_Anfang_RequirementDtl3> Requirement_Anfang_RequirementDtl3 { get; set; }
        public virtual DbSet<Requirement_Anfang_RequirementDtl5> Requirement_Anfang_RequirementDtl5 { get; set; }
        public virtual DbSet<Requirement_Anfang_RequirementDtl6> Requirement_Anfang_RequirementDtl6 { get; set; }
        public virtual DbSet<Requirement_Anfang_RequirementDtl7> Requirement_Anfang_RequirementDtl7 { get; set; }
        public virtual DbSet<Requirement_Bianchengjibianji_RequirementDtl2> Requirement_Bianchengjibianji_RequirementDtl2 { get; set; }
        public virtual DbSet<Requirement_Bianmajifuhe_RequirementDtl1> Requirement_Bianmajifuhe_RequirementDtl1 { get; set; }
        public virtual DbSet<Requirement_Bianmajifuhe_RequirementDtl3> Requirement_Bianmajifuhe_RequirementDtl3 { get; set; }
        public virtual DbSet<Requirement_Bianmajifuhe_RequirementDtl4> Requirement_Bianmajifuhe_RequirementDtl4 { get; set; }
        public virtual DbSet<Requirement_Bianmajifuhe_RequirementDtl5> Requirement_Bianmajifuhe_RequirementDtl5 { get; set; }
        public virtual DbSet<Requirement_Bianmajifuhe_RequirementDtl6> Requirement_Bianmajifuhe_RequirementDtl6 { get; set; }
        public virtual DbSet<Requirement_Bianmajifuhe_RequirementDtl7> Requirement_Bianmajifuhe_RequirementDtl7 { get; set; }
        public virtual DbSet<Requirement_Bianmajifuhe_RequirementDtl8> Requirement_Bianmajifuhe_RequirementDtl8 { get; set; }
        public virtual DbSet<Requirement_Bianmajifuhe_RequirementDtl9> Requirement_Bianmajifuhe_RequirementDtl9 { get; set; }
        public virtual DbSet<Requirement_Changdibuzhan_RequirementDtl2> Requirement_Changdibuzhan_RequirementDtl2 { get; set; }
        public virtual DbSet<Requirement_Cheliangzhanpinghui_RequirementDtl1> Requirement_Cheliangzhanpinghui_RequirementDtl1 { get; set; }
        public virtual DbSet<Requirement_Cheliangzhanpinghui_RequirementDtl10> Requirement_Cheliangzhanpinghui_RequirementDtl10 { get; set; }
        public virtual DbSet<Requirement_Cheliangzhanpinghui_RequirementDtl12> Requirement_Cheliangzhanpinghui_RequirementDtl12 { get; set; }
        public virtual DbSet<Requirement_Cheliangzhanpinghui_RequirementDtl13> Requirement_Cheliangzhanpinghui_RequirementDtl13 { get; set; }
        public virtual DbSet<Requirement_Cheliangzhanpinghui_RequirementDtl2> Requirement_Cheliangzhanpinghui_RequirementDtl2 { get; set; }
        public virtual DbSet<Requirement_Cheliangzhanpinghui_RequirementDtl31> Requirement_Cheliangzhanpinghui_RequirementDtl31 { get; set; }
        public virtual DbSet<Requirement_Cheliangzhanpinghui_RequirementDtl4> Requirement_Cheliangzhanpinghui_RequirementDtl4 { get; set; }
        public virtual DbSet<Requirement_Cheliangzhanpinghui_RequirementDtl5> Requirement_Cheliangzhanpinghui_RequirementDtl5 { get; set; }
        public virtual DbSet<Requirement_Cheliangzhanpinghui_RequirementDtl7> Requirement_Cheliangzhanpinghui_RequirementDtl7 { get; set; }
        public virtual DbSet<Requirement_Cheliangzhanpinghui_RequirementDtl8> Requirement_Cheliangzhanpinghui_RequirementDtl8 { get; set; }
        public virtual DbSet<Requirement_Cheliangzhanpinghui_RequirementDtl9> Requirement_Cheliangzhanpinghui_RequirementDtl9 { get; set; }
        public virtual DbSet<Requirement_Gongyingshangchailv_RequirementDtl1> Requirement_Gongyingshangchailv_RequirementDtl1 { get; set; }
        public virtual DbSet<Requirement_Group> Requirement_Group { get; set; }
        public virtual DbSet<Requirement_Guangkong_RequirementDtl1> Requirement_Guangkong_RequirementDtl1 { get; set; }
        public virtual DbSet<Requirement_Guangkong_RequirementDtl2> Requirement_Guangkong_RequirementDtl2 { get; set; }
        public virtual DbSet<Requirement_Guangkong_RequirementDtl3> Requirement_Guangkong_RequirementDtl3 { get; set; }
        public virtual DbSet<Requirement_Mianfangjidianfang_RequirementDtl1> Requirement_Mianfangjidianfang_RequirementDtl1 { get; set; }
        public virtual DbSet<Requirement_Mianfangjidianfang_RequirementDtl4> Requirement_Mianfangjidianfang_RequirementDtl4 { get; set; }
        public virtual DbSet<Requirement_Mianfangjidianfang_RequirementDtl5> Requirement_Mianfangjidianfang_RequirementDtl5 { get; set; }
        public virtual DbSet<Requirement_Mingjian_RequirementDtl1> Requirement_Mingjian_RequirementDtl1 { get; set; }
        public virtual DbSet<Requirement_Mingjian_RequirementDtl3> Requirement_Mingjian_RequirementDtl3 { get; set; }
        public virtual DbSet<Requirement_Mingjian_RequirementDtl5> Requirement_Mingjian_RequirementDtl5 { get; set; }
        public virtual DbSet<Requirement_Pankujijiagediaocha_RequirementDtl1> Requirement_Pankujijiagediaocha_RequirementDtl1 { get; set; }
        public virtual DbSet<Requirement_Pankujijiagediaocha_RequirementDtl2> Requirement_Pankujijiagediaocha_RequirementDtl2 { get; set; }
        public virtual DbSet<Requirement_Pankujijiagediaocha_RequirementDtl3> Requirement_Pankujijiagediaocha_RequirementDtl3 { get; set; }
        public virtual DbSet<Requirement_Pankujijiagediaocha_RequirementDtl4> Requirement_Pankujijiagediaocha_RequirementDtl4 { get; set; }
        public virtual DbSet<Requirement_Pankujijiagediaocha_RequirementDtl5> Requirement_Pankujijiagediaocha_RequirementDtl5 { get; set; }
        public virtual DbSet<Requirement_RequirementDtlLast> Requirement_RequirementDtlLast { get; set; }
        public virtual DbSet<Requirement_RequirementMst> Requirement_RequirementMst { get; set; }
        public virtual DbSet<Requirement_Shenfangjirijiliuzhi_RequirementDtl1> Requirement_Shenfangjirijiliuzhi_RequirementDtl1 { get; set; }
        public virtual DbSet<Requirement_Shenfangjirijiliuzhi_RequirementDtl4> Requirement_Shenfangjirijiliuzhi_RequirementDtl4 { get; set; }
        public virtual DbSet<Requirement_Shenfangjirijiliuzhi_RequirementDtl5> Requirement_Shenfangjirijiliuzhi_RequirementDtl5 { get; set; }
        public virtual DbSet<Requirement_Shenfangjirijiliuzhi_RequirementDtl6> Requirement_Shenfangjirijiliuzhi_RequirementDtl6 { get; set; }
        public virtual DbSet<Requirement_Wangluodiaoyan_RequirementDtl1> Requirement_Wangluodiaoyan_RequirementDtl1 { get; set; }
        public virtual DbSet<Requirement_Wangluodiaoyan_RequirementDtl2> Requirement_Wangluodiaoyan_RequirementDtl2 { get; set; }
        public virtual DbSet<Requirement_Wangluodiaoyan_RequirementDtl4> Requirement_Wangluodiaoyan_RequirementDtl4 { get; set; }
        public virtual DbSet<Requirement_Yanjiujishujufenxi_RequirementDtl2> Requirement_Yanjiujishujufenxi_RequirementDtl2 { get; set; }
        public virtual DbSet<Requirement_Yunshuzuche_RequirementDtl2> Requirement_Yunshuzuche_RequirementDtl2 { get; set; }
        public virtual DbSet<Requirement_Zuotanhui_RequirementDtl1> Requirement_Zuotanhui_RequirementDtl1 { get; set; }
        public virtual DbSet<Requirement_Zuotanhui_RequirementDtl2> Requirement_Zuotanhui_RequirementDtl2 { get; set; }
        public virtual DbSet<Requirement_Zuotanhui_RequirementDtl4> Requirement_Zuotanhui_RequirementDtl4 { get; set; }
        public virtual DbSet<Requirement_Zuotanhui_RequirementDtl5> Requirement_Zuotanhui_RequirementDtl5 { get; set; }
        public virtual DbSet<Requirement_Zuotanhui_RequirementDtl6> Requirement_Zuotanhui_RequirementDtl6 { get; set; }
        public virtual DbSet<SettlementCommitGroupDtl> SettlementCommitGroupDtl { get; set; }
        public virtual DbSet<SettlementDtl> SettlementDtl { get; set; }
        public virtual DbSet<SettlementMst> SettlementMst { get; set; }
        public virtual DbSet<SupplierMngAttachmentFile> SupplierMngAttachmentFile { get; set; }
        public virtual DbSet<SettlementCommitGroup> SettlementCommitGroup { get; set; }
        public virtual DbSet<Ana_HuizongbiaoRemak> Ana_HuizongbiaoRemak { get; set; }
        public virtual DbSet<Quotation_Group> Quotation_Group { get; set; }
        public virtual DbSet<SupplierEvaDepartment> SupplierEvaDepartment { get; set; }
        public virtual DbSet<SupplierEvaMainSubjects> SupplierEvaMainSubjects { get; set; }
        public virtual DbSet<SupplierEvaSubSubjects> SupplierEvaSubSubjects { get; set; }
        public virtual DbSet<Quotation_Chezhan_Dtl> Quotation_Chezhan_Dtl { get; set; }
        public virtual DbSet<Quotation_Qita1_Dtl> Quotation_Qita1_Dtl { get; set; }
        public virtual DbSet<Quotation_Qita2_Dtl> Quotation_Qita2_Dtl { get; set; }
        public virtual DbSet<Quotation_Yanjiu_Dtl> Quotation_Yanjiu_Dtl { get; set; }
        public virtual DbSet<Quotation_Zhichi_Dtl> Quotation_Zhichi_Dtl { get; set; }
        public virtual DbSet<Requirement_Mingjian_RequirementDtl4> Requirement_Mingjian_RequirementDtl4 { get; set; }
        public virtual DbSet<SupplierRequirementEmail> SupplierRequirementEmail { get; set; }
        public virtual DbSet<SupplierRequirementEmailFile> SupplierRequirementEmailFile { get; set; }
        public virtual DbSet<Quotation_Fuhe_Dtl> Quotation_Fuhe_Dtl { get; set; }
        public virtual DbSet<Requirement_Changdibuzhan_RequirementDtl1> Requirement_Changdibuzhan_RequirementDtl1 { get; set; }
        public virtual DbSet<Requirement_Cheliangzhanpinghui_RequirementDtl71> Requirement_Cheliangzhanpinghui_RequirementDtl71 { get; set; }
        public virtual DbSet<Requirement_Mianfangjidianfang_RequirementDtl2> Requirement_Mianfangjidianfang_RequirementDtl2 { get; set; }
        public virtual DbSet<Requirement_Bianmajifuhe_RequirementDtl71> Requirement_Bianmajifuhe_RequirementDtl71 { get; set; }
        public virtual DbSet<ApplyDtl_SettlementDtl> ApplyDtl_SettlementDtl { get; set; }
        public virtual DbSet<ApplyDtl_SettlementMst> ApplyDtl_SettlementMst { get; set; }
        public virtual DbSet<ApplyDtl_SupplierMng> ApplyDtl_SupplierMng { get; set; }
        public virtual DbSet<ApplyDtl_SupplierMngAttachmentFile> ApplyDtl_SupplierMngAttachmentFile { get; set; }
        public virtual DbSet<ProjectPerson> ProjectPerson { get; set; }
        public virtual DbSet<Projects> Projects { get; set; }
        public virtual DbSet<ApplyDtl_SettlementDtl_zhuijia_shoudong> ApplyDtl_SettlementDtl_zhuijia_shoudong { get; set; }
        public virtual DbSet<SettlementDtl_zhuijia_shoudong> SettlementDtl_zhuijia_shoudong { get; set; }
        public virtual DbSet<SupplierEvaAnswer> SupplierEvaAnswer { get; set; }
        public virtual DbSet<Mst_RoleType> Mst_RoleType { get; set; }
        public virtual DbSet<Requirement_Internal_Tangible_Qita1> Requirement_Internal_Tangible_Qita1 { get; set; }
        public virtual DbSet<Requirement_Internal_Intangible_Qita2> Requirement_Internal_Intangible_Qita2 { get; set; }
        public virtual DbSet<Constract> Constract { get; set; }
        public virtual DbSet<Quotation_Zhixing_Dtl> Quotation_Zhixing_Dtl { get; set; }
        public virtual DbSet<Requirement_Shenfangjirijiliuzhi_RequirementDtl2> Requirement_Shenfangjirijiliuzhi_RequirementDtl2 { get; set; }
        public virtual DbSet<SupplierMng> SupplierMng { get; set; }
        public virtual DbSet<SupplierAlter> SupplierAlter { get; set; }
        public virtual DbSet<ApplyDtl_FlowOrder> ApplyDtl_FlowOrder { get; set; }
        public virtual DbSet<FlowOrder> FlowOrder { get; set; }
        public virtual DbSet<RemindCancel> RemindCancel { get; set; }
        public virtual DbSet<ApplyFile> ApplyFile { get; set; }
        public virtual DbSet<ProjectCity> ProjectCity { get; set; }
        public virtual DbSet<Quotation_Biancheng_Dtl> Quotation_Biancheng_Dtl { get; set; }
        public virtual DbSet<Quotation_Group_Yusuan> Quotation_Group_Yusuan { get; set; }
        public virtual DbSet<Quotation_Yusuan_Dtl> Quotation_Yusuan_Dtl { get; set; }
        public virtual DbSet<Mst_UserInfoSetLog> Mst_UserInfoSetLog { get; set; }
        public virtual DbSet<Requirement_Yunshuzuche_RequirementDtl1> Requirement_Yunshuzuche_RequirementDtl1 { get; set; }
        public virtual DbSet<Mst_UserInfo> Mst_UserInfo { get; set; }
        public virtual DbSet<Requirement_Anfang_RequirementDtl4> Requirement_Anfang_RequirementDtl4 { get; set; }
        public virtual DbSet<Requirement_Bianmajifuhe_RequirementDtl2> Requirement_Bianmajifuhe_RequirementDtl2 { get; set; }
        public virtual DbSet<Requirement_Cheliangzhanpinghui_RequirementDtl11> Requirement_Cheliangzhanpinghui_RequirementDtl11 { get; set; }
        public virtual DbSet<Requirement_Cheliangzhanpinghui_RequirementDtl3> Requirement_Cheliangzhanpinghui_RequirementDtl3 { get; set; }
        public virtual DbSet<Requirement_Cheliangzhanpinghui_RequirementDtl6> Requirement_Cheliangzhanpinghui_RequirementDtl6 { get; set; }
        public virtual DbSet<Requirement_Mingjian_RequirementDtl2> Requirement_Mingjian_RequirementDtl2 { get; set; }
        public virtual DbSet<Requirement_Shenfangjirijiliuzhi_RequirementDtl3> Requirement_Shenfangjirijiliuzhi_RequirementDtl3 { get; set; }
        public virtual DbSet<Requirement_Mianfangjidianfang_RequirementDtl3> Requirement_Mianfangjidianfang_RequirementDtl3 { get; set; }
        public virtual DbSet<Requirement_Wangluodiaoyan_RequirementDtl3> Requirement_Wangluodiaoyan_RequirementDtl3 { get; set; }
        public virtual DbSet<Requirement_Zuotanhui_RequirementDtl3> Requirement_Zuotanhui_RequirementDtl3 { get; set; }
        public virtual DbSet<Requirement_Yanjiujishujufenxi_RequirementDtl1> Requirement_Yanjiujishujufenxi_RequirementDtl1 { get; set; }
        public virtual DbSet<Requirement_Bianchengjibianji_RequirementDtl1> Requirement_Bianchengjibianji_RequirementDtl1 { get; set; }
        public virtual DbSet<CustomerColumn> CustomerColumn { get; set; }
    }
}
