//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Purchase.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quotation_Zhixing_Dtl
    {
        public int QuotationId { get; set; }
        public int SeqNO { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public string IntoShopType { get; set; }
        public string ExecuteMode { get; set; }
        public string UserType { get; set; }
        public string ExistingOrPotential { get; set; }
        public string CustomerType { get; set; }
        public string ExcuteType { get; set; }
        public string AccountUnit { get; set; }
        public Nullable<decimal> ProposedPrice { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> yusuandanjia { get; set; }
        public Nullable<decimal> Count { get; set; }
        public string Remark { get; set; }
        public string InUserId { get; set; }
        public Nullable<System.DateTime> InDateTime { get; set; }
        public Nullable<bool> SelectedChk { get; set; }
        public Nullable<int> RequirementId { get; set; }
        public Nullable<int> RequirementSeqNO { get; set; }
        public string RequirementMstType { get; set; }
        public string RequirementRemark { get; set; }
    }
}
