//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Purchase.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requirement_Cheliangzhanpinghui_RequirementDtl13
    {
        public int RequirementId { get; set; }
        public int SeqNO { get; set; }
        public string luxingleixing { get; set; }
        public string hegeluyinbili { get; set; }
        public string wenjuanleixing { get; set; }
        public string zhengzhaoleixing { get; set; }
        public string hegezhengzhaoleixingbili { get; set; }
        public string xianchangdaochelv { get; set; }
        public string qitashuoming13 { get; set; }
        public string InUserId { get; set; }
        public Nullable<System.DateTime> InDateTime { get; set; }
    }
}
