//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Purchase.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requirement_Anfang_RequirementDtl2
    {
        public int RequirementId { get; set; }
        public int SeqNO { get; set; }
        public string AccessTime { get; set; }
        public string SoundRecordChk { get; set; }
        public string Videotape { get; set; }
        public string TrainingMode { get; set; }
        public string Appointment { get; set; }
        public string Avoid { get; set; }
        public string IntoShopAgain { get; set; }
        public string IntoShopAgainRate { get; set; }
        public string GPSLocationOrSMS { get; set; }
        public string MobileAnswer { get; set; }
        public string TimeMothod { get; set; }
        public string TelReturnVisit { get; set; }
        public string TelReturnVisitNumberRequirement { get; set; }
        public string OwnerreturenVisit { get; set; }
        public string FocusAnswer { get; set; }
        public string CustomerServiceLine { get; set; }
        public string RemarkDtl2 { get; set; }
        public string InUserId { get; set; }
        public Nullable<System.DateTime> InDateTime { get; set; }
    }
}
