//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Purchase.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requirement_Yunshuzuche_RequirementDtl1
    {
        public int RequirementId { get; set; }
        public int SeqNO { get; set; }
        public string feilei { get; set; }
        public string leixingpinpai { get; set; }
        public string guigexinghao { get; set; }
        public string pailiang { get; set; }
        public string peizhi { get; set; }
        public string changshangzhidaojia { get; set; }
        public string yanse { get; set; }
        public string shuliangmianji { get; set; }
        public string cheliangleibie { get; set; }
        public string chejiafanwei { get; set; }
        public string shiyongshijian { get; set; }
        public string qitashuoming1 { get; set; }
        public string InUserId { get; set; }
        public Nullable<System.DateTime> InDateTime { get; set; }
    }
}
