//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Purchase.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requirement_Internal_Intangible_Qita2
    {
        public int RequirementId { get; set; }
        public int SeqNO { get; set; }
        public string CostStruct { get; set; }
        public string Brand { get; set; }
        public string Specification { get; set; }
        public string Model { get; set; }
        public string Configuration { get; set; }
        public string AfterSaleContent { get; set; }
        public string AfterSalePeriod { get; set; }
        public string Warranty { get; set; }
        public string StaffLevel { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<System.DateTime> AcceptanceDate { get; set; }
        public Nullable<decimal> Count { get; set; }
        public string Remark { get; set; }
        public string InUserId { get; set; }
        public Nullable<System.DateTime> InDateTime { get; set; }
    }
}
