//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Purchase.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requirement_Mianfangjidianfang_RequirementDtl3
    {
        public int RequirementId { get; set; }
        public int SeqNO { get; set; }
        public string zhixingfenlei { get; set; }
        public string fangwenshichang { get; set; }
        public string yonghufenlei { get; set; }
        public string xianyouhuoqianzai { get; set; }
        public string kehufenlei { get; set; }
        public string goucheyugoushijianduan { get; set; }
        public string jutigoucheshijian { get; set; }
        public string shouhouweixiubaoyangshijian { get; set; }
        public string cheliangleibie { get; set; }
        public string pinpaifenlei { get; set; }
        public string chejiafanwei { get; set; }
        public string peiefenbu { get; set; }
        public string peieshuoming { get; set; }
        public string yangbenliang { get; set; }
        public string gongzuozhize { get; set; }
        public string baochoufangshi { get; set; }
        public string baochoujine { get; set; }
        public string chenggonglv { get; set; }
        public string mingdanlaiyuan { get; set; }
        public string qitashuoming3 { get; set; }
        public string InUserId { get; set; }
        public Nullable<System.DateTime> InDateTime { get; set; }
    }
}
