//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Purchase.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requirement_Mingjian_RequirementDtl5
    {
        public int RequirementId { get; set; }
        public int SeqNO { get; set; }
        public string shoucitijiaoshijianyaoqiu { get; set; }
        public string shoucitijiaotijiaoziliao { get; set; }
        public string shoucitijiaotijiaofangshi { get; set; }
        public string zuizhongtijiaoshijianyaoqiu { get; set; }
        public string zuizhongtijiaotijiaoziliao { get; set; }
        public string zuizhongtijiaotijiaofangshi { get; set; }
        public string qitashuoming5 { get; set; }
        public string InUserId { get; set; }
        public Nullable<System.DateTime> InDateTime { get; set; }
    }
}
