//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Purchase.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requirement_Bianmajifuhe_RequirementDtl2
    {
        public int RequirementId { get; set; }
        public int SeqNO { get; set; }
        public string fuheyaoqiu { get; set; }
        public string dianhuazixun { get; set; }
        public string dianhuhuifang { get; set; }
        public string yanbenbianji { get; set; }
        public string fuzhuyongpin { get; set; }
        public string bianmaleixing { get; set; }
        public string wenjuanbiancheng { get; set; }
        public string timushuliang { get; set; }
        public string zishushuliang { get; set; }
        public string peieshuoming { get; set; }
        public string yangbenliang { get; set; }
        public string abjuan { get; set; }
        public string abjuanyangbenlianghuobili { get; set; }
        public string wenjuanzuodaluyinfuhe { get; set; }
        public string wenjuanzuodaluyinfuheyangbenlianghuobili { get; set; }
        public string qitashuoming2 { get; set; }
        public string InUserId { get; set; }
        public Nullable<System.DateTime> InDateTime { get; set; }
    }
}
