//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Purchase.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requirement_Cheliangzhanpinghui_RequirementDtl10
    {
        public int RequirementId { get; set; }
        public int SeqNO { get; set; }
        public string zhixingfenlei { get; set; }
        public string zhixingchangdi { get; set; }
        public string fangwenshichang { get; set; }
        public string peixunfangshi { get; set; }
        public string genfangxueqiu { get; set; }
        public string genfangrenshu { get; set; }
        public string benpinmingdan { get; set; }
        public string rijixingshi { get; set; }
        public string rijizhouqi { get; set; }
        public string rijineirong { get; set; }
        public string liuzhixingshi { get; set; }
        public string liuzhizhouqi { get; set; }
        public string liuzhineirong { get; set; }
        public string qitashuoming10 { get; set; }
        public string InUserId { get; set; }
        public Nullable<System.DateTime> InDateTime { get; set; }
    }
}
