//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Purchase.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requirement_Pankujijiagediaocha_RequirementDtl3
    {
        public int RequirementId { get; set; }
        public int SeqNO { get; set; }
        public string fenlei { get; set; }
        public string leixingpinpai { get; set; }
        public string guigexinghao { get; set; }
        public string shuliangmianji { get; set; }
        public string shiyongshijian { get; set; }
        public string qitashuoming3 { get; set; }
        public string InUserId { get; set; }
        public Nullable<System.DateTime> InDateTime { get; set; }
    }
}
