//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Purchase.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requirement_Bianchengjibianji_RequirementDtl2
    {
        public int RequirementId { get; set; }
        public int SeqNO { get; set; }
        public string renyuangangwei { get; set; }
        public string gongzuoneirong { get; set; }
        public string gongzuodidian { get; set; }
        public string guigeyaoqiu { get; set; }
        public string zhiliangbiaozhun { get; set; }
        public string shuliang { get; set; }
        public string shijiananpai { get; set; }
        public string qitashuoming2 { get; set; }
        public string InUserId { get; set; }
        public Nullable<System.DateTime> InDateTime { get; set; }
    }
}
