//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Purchase.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requirement_Guangkong_RequirementDtl1
    {
        public int RequirementId { get; set; }
        public int SeqNO { get; set; }
        public string zhixingfenlei { get; set; }
        public string yaoyuechexingjiebie { get; set; }
        public string yaoyuechezhushenhe { get; set; }
        public string yaoyuechezhuzhenbie { get; set; }
        public string jindukongzhi { get; set; }
        public string chuchaijiankong { get; set; }
        public string xiangmupeixun { get; set; }
        public string luyinjianting { get; set; }
        public string ziliaohecha { get; set; }
        public string yangbenliang { get; set; }
        public string qitashuoming1 { get; set; }
        public string InUserId { get; set; }
        public Nullable<System.DateTime> InDateTime { get; set; }
    }
}
