//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Purchase.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requirement_Bianmajifuhe_RequirementDtl1
    {
        public int RequirementId { get; set; }
        public int SeqNO { get; set; }
        public string fuheyaoqiu { get; set; }
        public string fuheyaoqiuyangbenlianghuobili { get; set; }
        public string abjuan { get; set; }
        public string abjuanyangbenlianghuobili { get; set; }
        public string jishuwenjuanfuhe { get; set; }
        public string jishuwenjuanfuheyangbenlianghuobili { get; set; }
        public string wenjuanzuodaluyinfuhe { get; set; }
        public string wenjuanzuodaluyinfuheyangbenlianghuobili { get; set; }
        public string fuheyaoqiu1 { get; set; }
        public string fuheyaoqiuyangbenlianghuobili1 { get; set; }
        public string fuheneirong { get; set; }
        public string fuheneirongyangbenlianghuobili { get; set; }
        public string fuheshijian { get; set; }
        public string guangpankelu { get; set; }
        public string guangpankeluyangbenlianghuobili { get; set; }
        public string qitashuoming1 { get; set; }
        public string InUserId { get; set; }
        public Nullable<System.DateTime> InDateTime { get; set; }
    }
}
