//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Purchase.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requirement_Mingjian_RequirementDtl2
    {
        public int RequirementId { get; set; }
        public int SeqNO { get; set; }
        public string zhixingfenlei { get; set; }
        public string pinpaifenlei { get; set; }
        public string fangwenshichang { get; set; }
        public string zhixingnandu { get; set; }
        public string jindianfangshi { get; set; }
        public string jindianfangshibili { get; set; }
        public string yangbenliang { get; set; }
        public string baochoujine { get; set; }
        public string jindianguibiyaoqiu { get; set; }
        public string qitashuoming2 { get; set; }
        public string InUserId { get; set; }
        public Nullable<System.DateTime> InDateTime { get; set; }
    }
}
