//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Purchase.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requirement_Anfang_RequirementDtl7
    {
        public int RequirementId { get; set; }
        public int SeqNO { get; set; }
        public string Evaluator_Age { get; set; }
        public string Evaluator_Education { get; set; }
        public string Evaluator_Experience { get; set; }
        public string Evaluator_DriveChk { get; set; }
        public string Evaluator_FactDriveAge { get; set; }
        public string Evaluator_StaffRate { get; set; }
        public string Tech_Age { get; set; }
        public string Tech_Education { get; set; }
        public string Tech_CertificateRequirements { get; set; }
        public string Tech_Experience { get; set; }
        public string Tech_DriveChk { get; set; }
        public string Tech_StaffRate { get; set; }
        public string RemarkDtl7 { get; set; }
        public string InUserId { get; set; }
        public Nullable<System.DateTime> InDateTime { get; set; }
    }
}
