//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Purchase.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requirement_Anfang_RequirementDtl4
    {
        public int RequirementId { get; set; }
        public int SeqNO { get; set; }
        public string ExecuteType { get; set; }
        public string CustomerType { get; set; }
        public string BrandType { get; set; }
        public string IntoShopType { get; set; }
        public string CarChk { get; set; }
        public string IntoShopTypeRate { get; set; }
        public string CarType { get; set; }
        public string CarPriceRange { get; set; }
        public string CarLevel { get; set; }
        public string SampleCount { get; set; }
        public string Avoid { get; set; }
        public string IntoShopAgain { get; set; }
        public string IntoShopAgainRate { get; set; }
        public string Compensation { get; set; }
        public string ListSource { get; set; }
        public string RemarkDtl4 { get; set; }
        public string InUserId { get; set; }
        public Nullable<System.DateTime> InDateTime { get; set; }
    }
}
