//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Purchase.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requirement_Zuotanhui_RequirementDtl1
    {
        public int RequirementId { get; set; }
        public int SeqNO { get; set; }
        public string xingbie { get; set; }
        public string xingbiebili { get; set; }
        public string xueli { get; set; }
        public string nianling { get; set; }
        public string nianlingbili { get; set; }
        public string jiatingnianshouru { get; set; }
        public string jiatingyueshouru { get; set; }
        public string qitashuoming1 { get; set; }
        public string InUserId { get; set; }
        public Nullable<System.DateTime> InDateTime { get; set; }
    }
}
