//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Purchase.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requirement_Bianmajifuhe_RequirementDtl5
    {
        public int RequirementId { get; set; }
        public int SeqNO { get; set; }
        public string dianhuzixunyaoqiu { get; set; }
        public string dianhuazixunyangbenlianghuobili { get; set; }
        public string zixunfuheyaoqiu { get; set; }
        public string zixunfuheyaoqiuyangbenlianghuobili { get; set; }
        public string dianhuyuyueyaoqiu { get; set; }
        public string dianhuayuyueyangbenlianghuobili { get; set; }
        public string yuyuetixingfuhe { get; set; }
        public string yuyuetingxingfuheyangbenlianghuobili { get; set; }
        public string dianhuajiuyuanyaoqiu { get; set; }
        public string dianhuajiuyuanyangbenlianghuobili { get; set; }
        public string qitashuoming5 { get; set; }
        public string InUserId { get; set; }
        public Nullable<System.DateTime> InDateTime { get; set; }
    }
}
