//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Purchase.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requirement_Guangkong_RequirementDtl2
    {
        public int RequirementId { get; set; }
        public int SeqNO { get; set; }
        public string jinchudianbaoshi { get; set; }
        public string duanxindingweigpsdingwei { get; set; }
        public string jizhongjieting { get; set; }
        public string jindianqianyuyue { get; set; }
        public string shouhouchezhuhuifang { get; set; }
        public string kefuzhuanxinjieting { get; set; }
        public string huishouziliaojinduhecha { get; set; }
        public string huishouziliaozhengli { get; set; }
        public string yaoyueluyinjianji { get; set; }
        public string qitashuoming2 { get; set; }
        public string InUserId { get; set; }
        public Nullable<System.DateTime> InDateTime { get; set; }
    }
}
